<form class="" action="<?php echo $block->getBaseUrl().'crudimage/index/save'; ?>" id="kiwi-crudimage-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For KiwiCommerce Testimonials Module <a href="<?php echo $block->getBaseUrl().'crudimage/index/list'; ?>">(Visit List Page)</a></span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field company_name">
            <label class="label" for="company_name"><span>Company</span></label>
            <div class="control">
                <input name="company_name" id="company_name" title="company_name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field name">
            <label class="label" for="name"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field message">
            <label class="label" for="message"><span>Message</span></label>
            <div class="control">
                <textarea name="message" id="message" title="Message" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="field post">
            <label class="label" for="post"><span>Post</span></label>
            <div class="control">
                <textarea name="post" id="post" title="Post" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="field profile_pic">
            <label class="label" for="profile_pic"><span>Profile</span></label>
            <div class="control">
                <input name="profile_pic" id="profile_pic" title="Profile" value="" class="input-text" type="file">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>