<?php $collection = $block->getCrudimageCollection(); ?>
<?php if($collection->count() > 0): ?>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
    <table class="data table" id="crudimage-data-table">
        <caption class="table-caption">KiwiCommerce Testimonial Data</caption>
        <thead>
            <tr>
                <th scope="col" class="col Company">Company</th>
                <th scope="col" class="col name">Name</th>
                <th scope="col" class="col message">Message</th>
                <th scope="col" class="col post">Post</th>
                <th scope="col" class="col profile_pic">Profile Pic</th>
                <th scope="col" class="col created_at">Created At</th>
                <th scope="col" class="col actions">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($collection as $key => $data): ?>
                <tr>
                    <td data-th="Company" class="col company"><?php echo $data->getCompanyName(); ?></td>
                    <td data-th="Name" class="col name"><?php echo $data->getName(); ?></td>
                    <td data-th="Message" class="col message"><?php echo $data->getMessage(); ?></td>
                    <td data-th="Post" class="col post"><?php echo $data->getPost(); ?></td>
                    <td data-th="Profile" class="col profile_pic">
                        <?php $image = $data->getProfilePic(); ?>
                        <?php if (!empty($image)): ?>
                            <img width="70" height="70" src="<?php echo htmlspecialchars($block->getBaseUrl() . 'media/' . ltrim((string)$image, '/'), ENT_QUOTES, 'UTF-8'); ?>" alt="Image">
                        <?php else: ?>
                            <p>No Profile Pic</p>
                        <?php endif; ?>
                    </td>
                    <td data-th="Date" class="col created_at"><?php echo $data->getCreatedAt(); ?></td>
                    <td data-th="Actions" class="col actions">
                        <?php $id = ($data->getTestimonialId()) ? $data->getTestimonialId() : $data['testimonial_id']; ?>
                        <a href="<?php echo $block->getBaseUrl().'crudimage/index/view/id/'.$id; ?>" class="action view">
                            <span>View</span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <h2>We couldn't find any records</h2>
<?php endif; ?>