<?php
    $singleData = $block->getSingleData();
?>
<div>
    <h3>Title</h3>
    <p><?php echo $singleData->getTitle(); ?></p>   
</div>
<div>
    <h3>Author</h3>
    <p><?php echo $singleData->getAuthor(); ?></p>
</div>
<div>
    <h3>Content</h3>
    <?php if ($block->getFilterProvider() && $block->getFilterProvider()->getPageFilter()): ?>
        <p><?php echo $block->getFilterProvider()->getPageFilter()->filter($singleData->getContent()); ?></p>
    <?php else: ?>
        <p><?php echo $singleData->getContent(); ?></p>
    <?php endif; ?>
</div>
<div>
	<h3>Image</h3>
	<?php if($singleData->getImage()): ?>
        <img width="400" height="300" src="<?php echo $block->escapeUrl($block->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'media/' . ltrim($singleData->getImage(), '/')); ?>" alt="<?php echo $block->escapeHtml($singleData->getTitle()); ?>">
    <?php else: ?>
        <p>No Image</p>
    <?php endif; ?>
</div>
<div>
    <h3>Date</h3>
    <p><?php echo $singleData->getCreatedAt(); ?></p>
</div>